name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-compiles:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: cargo check
      run: cargo check

  build-linux:
    needs: check-compiles
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build for Linux
      run: cargo b -rv
    
    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: map-json-generator-2-linux
        path: target/release/map-json-generator-2
    
    - name: Install Lua
      run: sudo apt-get install -y lua5.4

    - name: Run the compiled binary
      run: cargo r -r -- --auto

    - name: Upload the generated map.json
      uses: actions/upload-artifact@v4
      with:
        name: map.json
        path: json/map.json
  
  build-windows:
    needs: check-compiles
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install MinGW
      run: sudo apt-get install -y mingw-w64

    - name: Add Windows target
      run: rustup target add x86_64-pc-windows-gnu
    
    - name: Build for Windows
      run: cargo b -rv --target x86_64-pc-windows-gnu

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: map-json-generator-2-windows.exe
        path: target/x86_64-pc-windows-gnu/release/map-json-generator-2.exe